project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
pull_request_assignees:
  - berdemozdemir
commit_message: 'chore: update %language% translations from Crowdin'
append_commit_message: 
files: []
