project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

pull_request_assignees: ['berdemozdemir']

commit_message: 'chore: update %language% translations from Crowdin'

append_commit_message: false

files:
  - source: /locales/en.po
    translation: /locales/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        tr: tr
        de: de
